### ISSUE TITLE
Please include links/references to the NEW Gitlab repos from the OLD Github ones, (for pop-awesome, et al)

### ISSUE THREAD

**Issue by nickgarber** [saltstack/community#104]
Example with POP-AWESOME

 - New Repo: https://gitlab.com/saltstack/pop/pop-awesome
 - Old Repo: https://github.com/saltstack/pop-awesome

**Comment by bryceml** [comment]
This should be done.  Let us know if there are any other repos we need to fix in a new issue or re-open this one.
