### ISSUE TITLE
Support for the Windows Event Logs

### ISSUE THREAD

**Issue by twangboy** [saltstack/community#33]
Look at the following:
- [x] Ability to log to the Windows Event Logs (log handler)
- [x] Ability to Query the Windows Event Logs
- [x] Ability to configure logging
- [ ] Shorten the names of the module and the functions

**Comment by cmcmarrow** [comment]
I have implemented the Ability to Query the Windows Event Logs. It works every well and its done via generators so memory does not explode.

**Comment by cmcmarrow** [comment]
I have implemented Ability to log to the Windows Event Logs (log handler). It checks to see if event data is valid before adding it to the log.

**Comment by cmcmarrow** [comment]
Windows does not give you much power to be able to config the log. All I can do is clear it and that's it.

**Comment by cmcmarrow** [comment]
I will push up win_event_viewer.py next week to salt once done with test. Then I'll write the salt state.

**Comment by cmcmarrow** [comment]
I used `win32evtlog`, `winerror` and `pywintypes` to make the module
