### ISSUE TITLE
Port https://github.com/saltstack/salt/pull/50545 to master

### ISSUE THREAD

**Issue by meaksh** [saltstack/community#67]
Port waiting for review: https://github.com/saltstack/salt/pull/55237

**Comment by dincamihai** [comment]
Mention: https://github.com/SUSE/spacewalk/issues/10017

**Comment by meaksh** [comment]
@dincamihai - I'm unassigning you from this card just in order to allow other people to tackle this one if they want.

Of course, in case you still want to keep this, please reassign yourself :-)

Btw!! I hope you had a nice Christmas and Happy new year!! :)

**Comment by vzhestkov** [comment]
Closing as https://github.com/saltstack/salt/pull/60228 was merged
