### ISSUE TITLE
Port batch-async to master

### ISSUE THREAD

**Issue by dincamihai** [saltstack/community#71]
- [x] saltstack/salt#51863 (incorporated)
- [x] https://github.com/saltstack/salt/pull/52519 (incorporater)
- [x] https://github.com/saltstack/salt/pull/50546

---

Instead of creating individual ports for each one of the PRs, we're going to push the final refactoring that we have in our `openSUSE-XXXX` branches at https://github.com/openSUSE/salt

- [ ] Final PR to `master`

**Comment by dincamihai** [comment]
Includes:
 - https://github.com/saltstack/community/issues/71
 - https://github.com/saltstack/community/issues/64
 - https://github.com/saltstack/community/issues/63

**Comment by dincamihai** [comment]
Mention: https://github.com/SUSE/spacewalk/issues/10017

**Comment by dincamihai** [comment]
WIP PR: https://github.com/saltstack/salt/pull/55268

**Comment by dincamihai** [comment]
TODO: test before removing WIP

**Comment by meaksh** [comment]
Since this card is not actually "Testing/Release" Working Group related and it has been hanging here quite long, I'm closing this card now even if the reference PRs are not yet ported.

I'm tracking this task internally at https://github.com/SUSE/spacewalk/issues/10017 , outside of this board.
