### ISSUE TITLE
Merge salt-toaster and upstream testing? [34]

### ISSUE THREAD

**Issue by brejoc** [saltstack/community#85]
https://github.com/openSUSE/salt-toaster

- [x] make salt-toaster public available
- [x] show progress on salt-toaster development to SaltStack upstream
- [ ] schedule a meeting with upstream to discuss about integrating toaster on upstream CI (maybe creating some jobs on the CI that uses the salt-toaster) https://github.com/saltstack/community/issues/88

**Comment by meaksh** [comment]
Currently "salt-toaster" needs some changes in order to allow running tests of the "master" branch. We will be reopening this issue and pushing this further as soon as we have "salt-toaster" back in shape!
